title: Evan Frenklak
description: Graduate Research Student <br> Electrical and Computer Engineering, UT Austin
author: Evan Frenklak
author_email: efrenklak@utexas.edu
google_analytics: G-????
theme: jekyll-theme-cayman
#theme: minima
